### ISSUE TITLE
Should be GenerateNextToken()?

### ISSUE THREAD

**Issue by RyanUnderhill** [saddam213/Genny#1]
Awesome project! I think you used GenerateNextTokenTop() because GenerateNextToken() wasn't available in the C# API yet.

https://github.com/saddam213/Genny/blob/a37c8561aa32a0c9e6b1d7d8b7ece5510e09c361/Genny/MainWindow.xaml.cs#L203

**Comment by saddam213** [comment]
Yeah mixup on my part, I was going to use `GenerateNextTokenTopKTopP` but I see its scheduled for removal, so will update to `GenerateNextToken`

**Comment by saddam213** [comment]
Master has now been updated to use correct sampling method :)

https://github.com/saddam213/Genny/commit/16d763a65710e90176a0867dc93b90cba854f4a7
